services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: dosealert
      POSTGRES_USER: natty
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
  pgdata:


