# Generated by Django 5.2.5 on 2025-08-11 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medication',
            old_name='user',
            new_name='userId',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='name',
        ),
        migrations.AddField(
            model_name='medication',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='frequency',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='medication',
            name='medication_specifications',
            field=models.JSONField(default=dict, help_text='Contains name, directions, sideEffects, purpose, and warnings'),
        ),
        migrations.AddField(
            model_name='medication',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
