# Generated by Django 5.2.5 on 2025-08-14 16:50

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0002_rename_user_medication_userid_remove_medication_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medication',
            old_name='userId',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='medication_specifications',
        ),
        migrations.AddField(
            model_name='medication',
            name='directions',
            field=models.TextField(blank=True, help_text='How to take the medication'),
        ),
        migrations.AddField(
            model_name='medication',
            name='dosage_amount',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01, message='Dosage must be greater than 0')]),
        ),
        migrations.AddField(
            model_name='medication',
            name='dosage_unit',
            field=models.CharField(choices=[('mg', 'mg'), ('g', 'g'), ('ml', 'ml'), ('pills', 'pills')], default='pills', max_length=20),
        ),
        migrations.AddField(
            model_name='medication',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, numbers, spaces, hyphens, and periods.', regex='^[a-zA-Z0-9\\s\\-\\.]+$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medication',
            name='purpose',
            field=models.TextField(blank=True, help_text='What the medication is for'),
        ),
        migrations.AddField(
            model_name='medication',
            name='side_effects',
            field=models.TextField(blank=True, help_text='Potential side effects'),
        ),
        migrations.AddField(
            model_name='medication',
            name='warnings',
            field=models.TextField(blank=True, help_text='Important warnings and precautions'),
        ),
    ]
