# Generated by Django 5.2.5 on 2025-08-11 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='schedules.schedule')),
            ],
        ),
    ]
