# Generated by Django 5.2.5 on 2025-08-11 14:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meds', '0002_rename_user_medication_userid_remove_medication_name_and_more'),
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='meds.medication'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='scheduled_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
